### ISSUE TITLE
Namespace conflict

### ISSUE THREAD

**Issue by lilith** [terjetyl/Simple.ImageResizer#1]
This package uses the 'ImageResizer' namespace, which has been used by the [ImageResizer](http://imageresizing.net) project since 2007.

**Comment by terjetyl** [comment]
The namespace has now been updated to Simple.ImageResizer

**Comment by lilith** [comment]
Thanks. Could you please add a clarification that this project is unrelated to ours? 

People are emailing questions about your project to support@imageresizing.net - the name apparently confuses them.

**Comment by terjetyl** [comment]
Ok. I have updated the Readme with a note. Let me know if it creates more confusion

**Comment by lilith** [comment]
Thanks, I appreciate it :)
